const today = new Date();
const currentYear = today.getFullYear();
const loginYear = 2021;

export const customerModule = {
  labelsList: [
    { id: 1, name: 'Banking', slug: 'banking', color: '#FF8C00' },
    { id: 2, name: 'Company', slug: 'company', color: '#00C4B4' },
    { id: 3, name: 'Payments', slug: 'payments', color: '#0F9AF7' },
  ],
  customerList: [
    {
      id: 1457690400,
      name: 'Alex Dolgove',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'alex-dolgove@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'Home' }],
      description: 'CEO',
      starred: false,
      labels: [2],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690401,
      name: 'Chelsea Johns',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'chelsea-johnss@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      description: 'CFO',
      starred: false,
      labels: [2, 1],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690402,
      name: 'Domnic Brown',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'domnic-brown@example.com',
      phones: [{ phone: '(215)-748-7855', label: 'home' }],
      description: 'Designer',
      starred: false,
      labels: [3],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690403,
      name: 'Domnic Harris',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'domnic-brown@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      description: 'PHP Developer',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690404,
      name: 'Garry Sobars',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'garry-sobars@example.com',
      phones: [{ phone: '(215)-659-8965', label: 'home' }],
      description: 'HR Manager',
      starred: true,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690405,
      name: 'Jeson Born',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'jeson-born@example.com',
      phones: [{ phone: '(215)-876-5434', label: 'home' }],
      description: 'Marketing Head',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690406,
      name: 'Jimmy Jo',
      dpUrl: 'https://via.placeholder.com/150g',
      email: 'jimmy-jo@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      description: 'BDO',
      starred: true,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690407,
      name: 'John Smith',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'john-smith@example.com',
      phones: [{ phone: '(215)-456-2346', label: 'home' }],
      description: 'CCO',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690408,
      name: 'Jonathan Modano',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'jonathan-modano@example.com',
      phones: [{ phone: '(215)-278-4357', label: 'home' }],
      description: 'Developer',
      starred: true,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690409,
      name: 'Kadir M',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'kadir-m@example.com',
      phones: [{ phone: '(215)-286-0788', label: 'home' }],
      description: 'UI-UX Designer',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690410,
      name: 'Ken Ramirez',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'ken-remirez@example.com',
      phones: [{ phone: '(215)-586-4676', label: 'home' }],
      description: 'CEO',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690500,
      name: 'Michael Dogov',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'michael-dogov@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      description: 'CEO',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690501,
      name: 'Stella Johnson',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'stella-johnson@example.com',
      phones: [{ phone: '(215)-745-2345', label: 'home' }],
      description: 'CFO',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690502,
      name: 'Steve Smith',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'steve-smith@example.com',
      phones: [{ phone: '(215)-748-3265', label: 'home' }],
      description: 'Designer',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690503,
      name: 'Noah Owens',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'noah-owens@example.com',
      phones: [{ phone: '(215)-756-3465', label: 'home' }],
      description: 'PHP Developer',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690404,
      name: 'Ellen Manning',
      dpUrl: '',
      email: 'ellen-manning@example.com',
      phones: [{ phone: '(215)-659-3246', label: 'home' }],
      description: 'HR Manager',
      starred: true,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690505,
      name: 'Angel Jones',
      dpUrl: '',
      email: 'angel-jones@example.com',
      phones: [{ phone: '(215)-876-3246', label: 'home' }],
      description: 'Marketing Head',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690506,
      name: 'Dollie Norton',
      dpUrl: '',
      email: 'dollie-norton@example.com',
      phones: [{ phone: '(215)-785-0967', label: 'home' }],
      description: 'BDO',
      starred: true,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690507,
      name: 'Joshua Brian',
      dpUrl: '',
      email: 'joshua-brian@example.com',
      phones: [{ phone: '(215)-456-0677', label: 'home' }],
      description: 'CCO',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690508,
      name: 'Amay Mathur',
      dpUrl: '',
      email: 'amay-mathur@example.com',
      phones: [{ phone: '(215)-278-5475', label: 'home' }],
      description: 'Developer',
      starred: true,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690509,
      name: 'Chris Mathew',
      dpUrl: '',
      email: 'chris-mathew@example.com',
      phones: [{ phone: '(215)-286-0456', label: 'home' }],
      description: 'UI-UX Designer',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
    {
      id: 1457690510,
      name: 'Nikki Johnson',
      dpUrl: '',
      email: 'nikki-johnson@example.com',
      phones: [{ phone: '(215)-586-2355', label: 'home' }],
      description: 'CEO',
      starred: false,
      labels: [],
      balance: 900,
      limit: 1000,
    },
  ],
};
